name: Cypress Tests

on: 
  workflow_dispatch:
    inputs:  
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $environment"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Write the cypress.env.json file
        # use quotes around the secret, as its value
        # is simply inserted as a string into the command
        run: |
          echo '${{ secrets.STAGING_VALUES }}' > cypress.env.json
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm i -D cypress
          command: npm run test
