name: Run Specific Cypress Tests

on: 
  workflow_dispatch:
    inputs:
      specs:
        description: Comma-separates spec filenames without spaces
        required: true
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: |
          echo "Environment: $environment"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Write the cypress.env.json file
        # use quotes around the secret, as its value
        # is simply inserted as a string into the command
        run: |
          echo '${{ secrets.STAGING_VALUES }}' > cypress.env.json

      - name: Get IP Address
        id: get_ip_address
        shell: pwsh
        run: |
          echo "ip_address=" + (curl -s https://ip4.me/api/ | cut -d ',' -f 2) >> "$GITHUB_OUTPUT"

      - name: ips
        id: ips
        shell: pwsh
        env: 
          HTTPS_PROXY: ${{ inputs.environment != 'production' && 'localhost:8888' || '' }}
          IP_ADDRESS:  ${{ steps.get_ip_address.outputs.ip_address }}
        run: |
          echo "name=ips_run" + (kubectl ["$env:IP_ADDRESS/32"])

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm i -D cypress
          spec: '${{ github.event.inputs.specs }}'
